name: Continuous Deployment

on:
  push:
    branches: [ main ]
  schedule:
    - cron: "0 11 * * *" # 11:00 Daily

jobs:

  build:
    runs-on: ubuntu-latest
    outputs:
      image: syntaqx/echo:latest
    steps:
      - run: echo "build goes here..."

  deployment:
    needs: [ build ]
    runs-on: ubuntu-latest
    environment:
      name: production
      url: 'http://echo.syntaqx.io'
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: false
    steps:
      - uses: actions/checkout@v3
      -
        name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
      -
        name: Save kubeconfig
        run: doctl kubernetes cluster kubeconfig save 1c672ab6-84e9-407c-89f3-09cd9b8d5ee5
      -
        name: Setup Kustomize
        run: |-
          curl -s "https://raw.githubusercontent.com/kubernetes-sigs/kustomize/master/hack/install_kustomize.sh" | bash
          mv kustomize /usr/local/bin/kustomize
          chmod +x /usr/local/bin/kustomize
      -
        name: Deploy
        run: |-
          # kustomize edit set image syntaqx/echo=${{ needs.build.outputs.image }}
          kustomize build . | kubectl apply -f -
